### ISSUE TITLE
$tring U?

### ISSUE THREAD

**Issue by sl0sh** [sakaki-/sakaki-tools#14]
Why can't you just clone get sakaki-tools?
I can't use intelmetool to verify because the gentoo install is so difficult.
why don't you just stay on wiki gentoo please?
thanks anyway

**Comment by sakaki-** [comment]
I'm sorry, I'm not quite sure I understand... are you trying to use `me_cleaner`, per [these instructions](https://wiki.gentoo.org/wiki/Sakaki's_EFI_Install_Guide/Disabling_the_Intel_Management_Engine)?
If so, then my [gentoo-on-rpi3-64bit](https://github.com/sakaki-/gentoo-on-rpi3-64bit) bootable image (for the RPi3 B/B+) contains all the necessary tools pre-installed.

Otherwise, this repo (`sakaki-tools`) is primarily for those building out a Gentoo system from scratch, following my wiki instructions [here](https://wiki.gentoo.org/wiki/Sakaki's_EFI_Install_Guide).

**Comment by sl0sh** [comment]
is there an easy way(compiled bin for windows or clone git install?) to execute "intelmetool" on the target machine without having to load gentoo?

**Comment by sakaki-** [comment]
OK I think I see what you're looking for. `intelmetool` is, afaik, a tool runnable on Linux OSes only; it is relatively easy to compile for any such system (Ubuntu etc.) As such, you could boot e.g. a live-USB of Ubuntu on your PC, and then compile it there.

As for pre-compiled binaries, or Windows ports, I'm the wrong person to ask I'm afraid. Perhaps post an issue in [zamaudio/intelmetool](https://github.com/zamaudio/intelmetool); it is a retired repo but you are more likely to get a useful response there.

Sorry I can't be of any more assistance with this. Good luck!

Closing, sakaki.
